import Link from "next/link";
import { notFound } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { updateTaskStatus } from "../../my-work/actions";

function duration(minutes:number){return `${Math.floor(minutes/60)}h ${minutes%60}m`;}
export default async function TaskPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{submitted?:string,error?:string}>}){
  const {id}=await params;
  const p=await searchParams;
  const {supabase,profile}=await requireProfile();
  const {data:t}=await supabase.from("tasks").select("*,assignee:profiles!tasks_assigned_to_fkey(full_name,email),creator:profiles!tasks_created_by_fkey(full_name),reviewer:profiles!tasks_current_reviewer_id_fkey(full_name),task_approval_steps(step_order,reviewer_id,profiles!task_approval_steps_reviewer_id_fkey(full_name)),task_submissions(id,version_number,status,completion_note,external_link,time_spent_minutes,submitted_at,submission_files(id,file_name,storage_path,file_size),submission_approval_steps(step_order,status,reviewer_id,profiles!submission_approval_steps_reviewer_id_fkey(full_name)),submission_reviews(decision,comment,created_at,profiles!submission_reviews_reviewer_id_fkey(full_name)))").eq("id",id).maybeSingle();
  if(!t) notFound();
  const own=t.assigned_to===profile.id;
  const canSubmit=own&&["not_started","in_progress","blocked","changes_requested","rejected"].includes(t.status);
  const submissions=(t.task_submissions||[]).sort((a:any,b:any)=>b.version_number-a.version_number);
  return <div className="grid">
    <div className="actions between"><div><h1>{t.title}</h1><p className="muted">Assigned to {t.assignee?.full_name}</p></div>{canSubmit&&<Link href={`/tasks/${id}/submit`} className="btn">Submit work for review</Link>}</div>
    {p.submitted&&<p className="notice">Work submitted. It is now waiting for review.</p>}{p.error&&<p className="error">{p.error}</p>}
    <section className="card grid grid2"><div><strong>Description</strong><p>{t.description}</p><strong>Expected output</strong><p>{t.expected_output||"Not specified"}</p><strong>Required evidence</strong><p>{t.required_evidence||"Not specified"}</p></div><div><p><strong>Priority:</strong> {t.priority}</p><p><strong>Due:</strong> {new Date(t.due_date).toLocaleString()}</p><p><strong>Created by:</strong> {t.creator?.full_name}</p><p><strong>Status:</strong> <span className="badge">{t.status.replaceAll("_"," ")}</span></p><p><strong>Current reviewer:</strong> {t.reviewer?.full_name||"Review complete / not started"}</p>{t.blocker_reason&&<p className="error"><strong>Blocker:</strong> {t.blocker_reason}</p>}</div></section>
    <section className="card"><h2>Configured approval chain</h2><div className="stepper">{(t.task_approval_steps||[]).sort((a:any,b:any)=>a.step_order-b.step_order).map((s:any)=><div className="step waiting" key={`${s.step_order}-${s.reviewer_id}`}><strong>Step {s.step_order}</strong><span>{s.profiles?.full_name}</span></div>)}{!t.task_approval_steps?.length&&<p className="error">No reviewers configured. Edit or recreate this task with a reviewer.</p>}</div></section>
    {own&&["not_started","in_progress","blocked"].includes(t.status)&&<section className="card"><h2>Update work status</h2><form action={updateTaskStatus} className="form"><input type="hidden" name="id" value={t.id}/><label className="label">Status<select className="select" name="status" defaultValue={t.status}><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option></select></label><label className="label">Blocker reason<textarea className="textarea" name="blocker_reason" defaultValue={t.blocker_reason||""}/></label><button className="btn">Save status</button></form></section>}
    <section className="card"><h2>Submission history</h2>{submissions.map((s:any)=><article className="submission" key={s.id}><div className="actions between"><div><strong>Version {s.version_number}</strong> · <span className="badge">{s.status.replaceAll("_"," ")}</span></div><small className="muted">{new Date(s.submitted_at).toLocaleString()}</small></div><p>{s.completion_note}</p><p className="muted">Time reported: {duration(s.time_spent_minutes)} · Files: {s.submission_files?.length||0}</p>{s.external_link&&<a className="textlink" target="_blank" rel="noreferrer" href={s.external_link}>Open external link</a>}<div className="stepper">{(s.submission_approval_steps||[]).sort((a:any,b:any)=>a.step_order-b.step_order).map((step:any)=><div className={`step ${step.status}`} key={`${s.id}-${step.step_order}`}><strong>{step.profiles?.full_name}</strong><span>{step.status.replaceAll("_"," ")}</span></div>)}</div>{(s.submission_reviews||[]).map((r:any)=><div className="history" key={`${r.created_at}-${r.decision}`}><strong>{r.profiles?.full_name}</strong> — {r.decision.replaceAll("_"," ")}<div>{r.comment||"No comment"}</div></div>)}</article>)}{!submissions.length&&<p className="muted">No work has been submitted yet.</p>}</section>
  </div>;
}
