import { NextRequest,NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { createClient } from "@/lib/supabase/server";
export async function GET(req:NextRequest){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return new NextResponse("Unauthorized",{status:401});
 const {data:profile}=await supabase.from("profiles").select("organization_id,role").eq("id",user.id).maybeSingle();if(!profile||profile.role!=="admin")return new NextResponse("Forbidden",{status:403});
 const u=req.nextUrl.searchParams;const from=u.get("from")||new Date(Date.now()-6*86400000).toISOString().slice(0,10),to=u.get("to")||new Date().toISOString().slice(0,10),format=u.get("format")||"csv";
 const {data,error}=await supabase.from("daily_logs").select("work_date,attendance_status,status,total_minutes,employee_id,profiles!daily_logs_employee_id_fkey(full_name,team_id),daily_log_items(description,duration_minutes,quantity,unit,work_categories(name))").eq("organization_id",profile.organization_id).gte("work_date",from).lte("work_date",to).order("work_date");if(error)return new NextResponse(error.message,{status:400});
 let rows=data??[];const team=u.get("team"),employee=u.get("employee");if(team)rows=rows.filter((x:any)=>{const p=Array.isArray(x.profiles)?x.profiles[0]:x.profiles;return p?.team_id===team});if(employee)rows=rows.filter((x:any)=>x.employee_id===employee);
 const flat=rows.flatMap((x:any)=>{const p=Array.isArray(x.profiles)?x.profiles[0]:x.profiles;const items=x.daily_log_items??[];return items.length?items.map((i:any)=>{const c=Array.isArray(i.work_categories)?i.work_categories[0]:i.work_categories;return {Date:x.work_date,Employee:p?.full_name||"",Attendance:x.attendance_status,Category:c?.name||"Other",Description:i.description,Minutes:i.duration_minutes||0,Quantity:i.quantity??"",Unit:i.unit||"",LogStatus:x.status}}):[{Date:x.work_date,Employee:p?.full_name||"",Attendance:x.attendance_status,Category:"",Description:"",Minutes:0,Quantity:"",Unit:"",LogStatus:x.status}]});
 if(format==="xlsx"){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(flat),"Work Report");const bytes=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});return new NextResponse(bytes,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename=work-report-${from}-to-${to}.xlsx`}})}
 const headers=Object.keys(flat[0]||{Date:"",Employee:"",Attendance:"",Category:"",Description:"",Minutes:"",Quantity:"",Unit:"",LogStatus:""});const esc=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[headers.join(","),...flat.map((r:any)=>headers.map(h=>esc(r[h])).join(","))].join("\n");return new NextResponse(csv,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename=work-report-${from}-to-${to}.csv`}})
}
